# Generated by Django 2.1.5 on 2019-02-04 19:48

import apprentice_learner.models
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', picklefield.fields.PickledObjectField(editable=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('num_request', models.IntegerField(default=0)),
                ('num_train', models.IntegerField(default=0)),
                ('num_check', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('head', models.TextField(blank=True, validators=[apprentice_learner.models.valid_py])),
                ('conditions', models.TextField(blank=True, validators=[apprentice_learner.models.valid_py])),
                ('effects', models.TextField(blank=True, validators=[apprentice_learner.models.valid_py])),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT_PROJECT', max_length=200)),
                ('numerical_epsilon', models.FloatField(default=0.0)),
                ('feature_set', models.ManyToManyField(blank=True, related_name='feature_sets', to='apprentice_learner.Operator')),
                ('function_set', models.ManyToManyField(blank=True, related_name='function_sets', to='apprentice_learner.Operator')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apprentice_learner.Project'),
        ),
    ]
