# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentice_learner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionset',
            name='features',
        ),
        migrations.RemoveField(
            model_name='actionset',
            name='functions',
        ),
        migrations.AlterField(
            model_name='agent',
            name='action_set',
            field=models.CharField(default='tutor knowledge', max_length=200),
        ),
        migrations.DeleteModel(
            name='ActionSet',
        ),
        migrations.DeleteModel(
            name='PyFunction',
        ),
    ]
