# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentice_learner', '0002_auto_20170509_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='action_set',
            field=models.CharField(max_length=200),
        ),
    ]
