# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 20:28
from __future__ import unicode_literals

import apprentice_learner.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprentice_learner', '0004_operator_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='feature_and_function_set',
        ),
        migrations.AddField(
            model_name='agent',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apprentice_learner.Project'),
        ),
        migrations.AddField(
            model_name='operator',
            name='head',
            field=models.TextField(blank=True, validators=[apprentice_learner.models.valid_py]),
        ),
        migrations.AddField(
            model_name='project',
            name='feature_set',
            field=models.ManyToManyField(blank=True, related_name='feature_sets', to='apprentice_learner.Operator'),
        ),
        migrations.AddField(
            model_name='project',
            name='function_set',
            field=models.ManyToManyField(blank=True, related_name='function_sets', to='apprentice_learner.Operator'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='conditions',
            field=models.TextField(blank=True, validators=[apprentice_learner.models.valid_py]),
        ),
        migrations.AlterField(
            model_name='operator',
            name='effects',
            field=models.TextField(blank=True, validators=[apprentice_learner.models.valid_py]),
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
