# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentice_learner', '0005_auto_20170918_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='action_set',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='DEFAULT_PROJECT', max_length=200),
        ),
    ]
