# Generated by Django 2.1.5 on 2019-02-04 19:48

import apprentice_learner.models
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', picklefield.fields.PickledObjectField(editable=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('num_request', models.IntegerField(default=0)),
                ('num_train', models.IntegerField(default=0)),
                ('num_check', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
    ]
